authory/urls.py
from django.urls import path
from . import views
app_name='authory'
urlpatterns = [
    path('login/',views.wmlogin,name='wmlogin'),
    path('logout/',views.wmlogout,name='wmlogout'),
    path('register/',views.register,name='register'),
    path('emailcode',views.email_code,name='emailcode'),
]

blog/urls.py
from django.urls import path, include

from authory.urls import app_name
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index,name='index'),
    path('blog/search', views.search, name='search'),
    path('blog/<int:blog_id>', views.blog_view, name='blog_view'),
    path('blog/<pub>',views.public, name='blog_view'),
    path('blog/comment/pub',views.pub_comment,name='pub_comment'),

]

csdn_django/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authory/',include('authory.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User=get_user_model()
# Create your models here.
class BlogCategory(models.Model):
    name=models.CharField(max_length=100,verbose_name='分类名称')
    class Meta:
        verbose_name='博客分类'
        verbose_name_plural='博客分类'
    def __str__(self):
        return self.name

class Blog(models.Model):
    title=models.CharField(max_length=100,verbose_name='博客标题')
    content=models.TextField(verbose_name='博客内容')
    category=models.ForeignKey(BlogCategory,on_delete=models.CASCADE)
    pub_date=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    class Meta:
        verbose_name='博客'
        verbose_name_plural='博客'
        ordering=['-pub_date']
    def __str__(self):
        return self.title

class BlogComment(models.Model):
    content=models.TextField(verbose_name='评论内容')
    pub_date=models.DateTimeField(auto_now_add=True)
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='comments',verbose_name='所属博客')
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    class Meta:
        verbose_name='博客评论'
        verbose_name_plural='博客评论'
        ordering = ['-pub_date']
    def __str__(self):
        return self.content

blog/forms.py
from django import forms
class PubBlogForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    category = forms.IntegerField()

blog/views.py
from django.db.models import Q
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import title
from django.views.decorators.http import require_http_methods,require_POST,require_GET
from unicodedata import category
from .forms import PubBlogForm
from .models import Blog,BlogComment,BlogCategory
from django.http import HttpResponse, JsonResponse


# Create your views here.
def index(request):
    blogs=Blog.objects.all()
    return render(request, 'index.html',context={'blogs':blogs})

def blog_view(request,blog_id):
    try:
        blog=Blog.objects.get(pk=blog_id)
    except Exception as e:
        blog=None
    return render(request, 'blog.html',context={'blog':blog})

# @login_required(login_url='/authory/login/')
@require_http_methods(["GET", "POST"])
@login_required()
def public(request,pub):
    if request.method== 'GET':
        categories=BlogCategory.objects.all()
        return render(request, 'public.html',context={'categories':categories})
    else:
        form=PubBlogForm(request.POST)
        if form.is_valid():
            title=form.cleaned_data.get('title')
            content=form.cleaned_data.get('content')
            category_id=form.cleaned_data.get('category')
            blog=Blog.objects.create(title=title,content=content,category_id=category_id,author=request.user)
            return JsonResponse({'code':200,'message':'success','data':{'blog_id':blog.id}})
        else:
            print('false')
            return JsonResponse({'code':400,'message':'fail'})


@require_POST
@login_required()
def pub_comment(request):
    blog_id = request.POST.get('blog_id')
    content = request.POST.get('content')
    BlogComment.objects.create(blog_id=blog_id, content=content, author=request.user)
    return redirect(reverse('blog:blog_view', kwargs={'blog_id': blog_id}))

@require_GET
def search(request):
    #通过 /search?q=xxx 获取参数
    q = request.GET.get('q')
    #博客标题和内容中查找
    blogs = Blog.objects.filter(Q(title__icontains=q)|Q(content__icontains=q)).all()
    return render(request,'index.html',context={'blogs':blogs})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}wqianlai_blog</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
{#    <script src="{% static 'bootstrap-5.0.2/bootstrap.min.js' %}"></script>#}
    <link rel="stylesheet" href="{% static 'bootstrap-5.0.2/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-5.0.2/css/base.css' %}">
       {% block header %}{% endblock %}
</head>
<body>
<!-- 确保在<body>中添加此元素 -->
<header class="p-3 bg-light text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/static" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use  href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
          <li><a href="{% url 'blog:blog_view' pub='public' %}" class="nav-link px-2 text-secondary">博客发布</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'blog:search' %}" method="GET">
          <input type="search" name="q" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

          {% if user.is_authenticated %}
              <div class="dropdown text-end">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="true">
                    <img src="{% static 'img/dog.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                  </a>
                  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                    <li><a class="dropdown-item" href="{% url 'authory:wmlogout' %}">退出登录</a></li>
                  </ul>
                </div>
          {% else %}
               <div class="text-end">
                  <a href="{% url 'authory:register' %}" class="btn btn-outline-primary me-2">注册</a>
                  <a href="{% url 'authory:wmlogin' %}" class="btn btn-primary">登录</a>
                </div>
          {% endif %}

      </div>
    </div>
  </header>
<main>
    <div class="container bg-white m-auto mt-3 rounded-2 row p-3">
        {% block main %}{% endblock %}
    </div>
</main>
</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% block title %}{{ blog.title }}{% endblock %}
{% block main %}
    <h1 class="p-3"> 博客详情</h1>
        <hr>
        <div>
            <img src="{% static '/img/dog.png' %}" width="30" height="30" class="rounded-circle" alt="" >
            <span class="ms-1">{{ blog.author.username }}</span>
            <span class="ms-1">在</span>
            <span class="create-time ms-2">{{ blog.pub_time|date:"Y年M月D日h时i分"}}</span>发布
        </div>
        <hr class="mt-2">
        <div class="py-1">{{ blog.content|safe }}</div>
        <span>hola</span>
        <hr class="mt-2">
        <h3>comments({{ blog.comments.all|length }}):</h3>
        <form action="{% url 'blog:pub_comment'%}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="blog_id" value="{{ blog.id }}">        
         <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="内容" name="content">
          <button class="btn btn-outline-secondary " type="submit" id="button-addon2">提交</button>
        </div>
    </form>
        <hr>
        <div class="py-2 d-flex justify-content-between">
            <div><img src="{% static 'img/dog.png' %}" width="40" height="40" alt="">
            <span>hola</span>
            </div>
            <span>{{ blog.comments.pub_time|date:"Y年M月D日h时i分" }}</span>
        </div>
            <ul class="list-group">
            {% for comment in blog.comments.all %}
          <li class="list-group-item">{{ comment.content }}</li>
            {% endfor %}
            </ul>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block main %}
    <h1 class="p-3"> 博客展示</h1>
        <div class="row row-cols-2 row-gap-4">
        {% for blog in blogs %}
        <div class="col">
        <div class="card">
            
          <div class="card-header">
             <h5 class="card-title">{{ blog.author.username }}在{{ blog.pub_time|date:"Y年M月D日h时i分" }}</h5>
          </div>
          <div class="card-body">
            
            <p class="card-text">{{ blog.content|striptags|truncatechars:50 }}</p>
             <a href="{% url 'blog:blog_view' blog_id=blog.id%} ">{{ blog.title }}</a>
          </div>
          </div>
          </div>
       {% endfor %}
        </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
{% block main %}
     <div style="width: 300px " class="m-auto">
            <h1 class="p-3">登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="text-start d-block">Email</label>
                <input type="email" name="email" class="form-control" placeholder="email">
            </div>
            <div class="mb-3">
                <label class="text-start d-block">密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="mb-3">
                   <div class="form-check">
              <input class="form-check-input" type="checkbox" name="remeber" value="True" id="flexCheckDefault">
                <label class="form-check-label text-start d-block" for="flexCheckDefault">
                默认记住
              </label>
            </div> 
            </div>  
            <div class="mb-3">
                <button type="submit" class="btn btn-primary w-100">登录</button>
            </div>

            
        </form>
        </div>

{% endblock %}

templates/public.html
{% extends 'base.html' %}

{% block title %}发布{% endblock %}
{% block header %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="https://unpkg.com/@wangeditor/editor@latest/dist/index.js"></script>
    <script src="{% static 'js/public_base.js' %}"></script>
    <link
      href="https://unpkg.com/@wangeditor/editor@latest/dist/css/style.css"
      rel="stylesheet"
    />


<style>
  #editor—wrapper {
    border: 1px solid #ccc;
    z-index: 100; /* 按需定义 */
  }
  #toolbar-container {
    border-bottom: 1px solid #ccc;
  }
  #editor-container {
    height: 500px;
  }
</style>
{% endblock %}
{% block main %}
            <h1 class="p-3"> 博客发布</h1>
        <div class="p-3">
            <form action="" method="post">
            {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">标题</label>
                    <input type="text" class="form-control" name="title" placeholder="请输入标题">
                </div>
               <div class="mb-3">
                    <label class="form-label">分类</label>
                   <select name="category" class="form-select" id="category-select">
                       {% for category in categories %}
                           <option value="{{ category.id }}">{{ category.name }}</option>
                       {% endfor %}
                   </select>
                </div>
                <div class="mb-3">
                    <label class="form-label">内容</label>
                            <div id="editor—wrapper">
          <div id="toolbar-container"><!-- 工具栏 --></div>
          <div id="editor-container"><!-- 编辑器 --></div>
        </div>
                </div>
                <div class="mb-3 text-end">
                    <button type="submit" class="btn btn-primary " id="submit-up">发布</button>
                </div>
            </form>
        </div>
    <script>
        hljs.highlightAll();
    </script>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}注册{% endblock %}

{% block header%}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block main %}
   
      <div style="width: 300px " class="m-auto">
            <h1 class="p-3">注册</h1>
        <form action="" method="post">
             {% csrf_token %}
            <div class="mb-3">
                <label class="text-start d-block">用户名</label>
                <input type="text" name="username" id="username" class="form-control" placeholder="用户名" autocomplete="username">
            </div>
            <div class="mb-3">
                <label class="text-start d-block">邮箱</label>
                <input type="email" id="email" name="email" class="form-control" placeholder="邮箱" autocomplete="email">
            </div>
            <div class="input-group mt-3">
              <input type="text" name="emailcode" class="form-control" placeholder="验证码">
              <button id="email-code" class="btn btn-primary" type="button" aria-autocomplete="off">
                获取验证码
              </button>
            </div>
            <div class="mb-3">
                <label class="text-start d-block">密码</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="密码" autocomplete="current_password">
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary w-100">注册</button>
            </div>


        </form>
        </div>

{% endblock %}
